<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WINDOW" failures="1" tests="2" name="Login Test" time="39.632" errors="0" timestamp="2025-09-17T14:05:40 IST">
  <testcase classname="com.orangehrm.LoginTest" name="loginDataDrivenTest" time="31.972">
    <failure type="java.lang.AssertionError" message="Exception during login for: Adm">
      <![CDATA[java.lang.AssertionError: Exception during login for: Adm
at com.orangehrm.LoginTest.loginDataDrivenTest(LoginTest.java:108)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDrivenTest -->
  <testcase classname="com.orangehrm.LoginTest" name="loginDataDrivenTest" time="4.606"/>
</testsuite> <!-- Login Test -->
